# Generated by Django 3.0 on 2020-05-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinId', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('length', models.PositiveIntegerField()),
                ('sequence', models.TextField()),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_motif_positions', models.TextField()),
                ('count', models.PositiveIntegerField()),
                ('zscore', models.FloatField()),
                ('ratio', models.FloatField()),
                ('pvalue', models.FloatField()),
                ('alignment', models.TextField()),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Motif')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Protein')),
            ],
        ),
    ]
